routes/admin.php
<?php

use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\Auth\LoginController;
use App\Http\Controllers\Admin\Auth\ForgotPasswordController;
use App\Http\Controllers\Admin\Auth\ResetPasswordController;
use App\Http\Controllers\Admin\ClassController;
use App\Http\Controllers\Admin\ClassRegisterController;
use App\Http\Controllers\Admin\CommonApiController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\ContractController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\admin\SubjectCategoryController;
use App\Http\Controllers\Admin\SubjectController;
use App\Http\Controllers\Admin\UserController;
use Illuminate\Support\Facades\Route;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

Route::get('login', [LoginController::class, 'showLoginForm'])->name('login');
Route::post('login', [LoginController::class, 'login']);

Route::get('logout', [LoginController::class, 'logout'])->name('logout');
// Route::get('logout', [LoginController::class, 'logout']); // @Todo Remove logout GET method

Route::get('password/reset', [ForgotPasswordController::class, 'showLinkRequestForm'])->name('password.request');
Route::post('password/email', [ForgotPasswordController::class, 'sendResetLinkEmail'])->name('password.email');

Route::get('password/reset/{token}', [ResetPasswordController::class, 'showResetForm'])->name('password.reset');
Route::post('password/reset', [ResetPasswordController::class, 'reset'])->name('password.update');

Route::group(['prefix'=>'','as'=>'','middleware' => ['admin.auth']], function(){
    Route::get('dashboard', [DashboardController::class, 'dashboard'])->name("dashboard");
    Route::resource('contracts', ContractController::class);
    Route::resource('subject-categories', SubjectCategoryController::class);
    Route::resource('subjects', SubjectController::class);
    Route::resource('classes', ClassController::class);
    Route::resource('roles', RoleController::class);
    Route::resource('classes-register', ClassRegisterController::class);
    Route::resource('admins', AdminController::class);
    Route::get('api/admins', [AdminController::class, 'getData'])->name('admins.api');
    Route::get('api/classes-register', [ClassRegisterController::class, 'getData'])->name('classes-register.api');
    Route::post('api/classes-register/{id}/calendar', [ClassRegisterController::class, 'addCalendar'])->name('api.classes-register.calendar');
    Route::get('api/classes-register/{id}/filter/tutors', [ClassRegisterController::class, 'filterTutor'])->name('api.classes-register.filter');
    Route::post('api/classes-register/{id}/class/{user_id}/assign', [ClassRegisterController::class, 'assignClass'])->name('api.classes-register.assign');
    Route::delete('api/classes-register/calendar/{id}/delete', [ClassRegisterController::class, 'deleteCalendar'])->name('api.classes-register.calendar.delete');
    Route::get('api/classes-register/{id}/userAssigned', [ClassRegisterController::class, 'getUserAssignee'])->name('api.classes-register.userAssigned');
    Route::get('api/administrative-units', [CommonApiController::class, 'getAdministrativeUnits'])->name('api.administrative-units');
    Route::get('api/calendar/events/{modal_id}/get', [CommonApiController::class, 'getEvents'])->name('api.calendar.events');
    Route::get("profile", [AdminController::class, "profile"])->name("profile");
    Route::post("profile/store", [AdminController::class, "storeProfile"])->name("profile.store");
    Route::post("avatar/store", [AdminController::class, "storeAvatar"])->name("avatar.store");
    Route::get("security", [AdminController::class, "security"])->name("security");
    Route::post("security/store", [AdminController::class, "storeSecurity"])->name("security.store");
    Route::get("users", [UserController::class, "index"])->name("users.index");
    Route::POST("users/{id}/update/status", [UserController::class, "updateStatus"])->name("users.update.status");
    Route::POST("users/{id}/update/honnor", [UserController::class, "updateHonnor"])->name("users.update.honnor");
    Route::get("users/{id}/info", [UserController::class, "getInfoUsers"])->name("users.info");
    Route::get("api/users", [UserController::class, "getData"])->name("users.getData");
});

routes/web.php
<?php

use App\Http\Controllers\Admin\CommonApiController;
use App\Http\Controllers\frontend\ClassRegisterController;
use App\Http\Controllers\Frontend\HomeController;
use App\Http\Controllers\Frontend\UserController;

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get("/",[HomeController::class, "index"])->name("index");
Route::get("/contract",[HomeController::class, "contract"])->name("contract");
Route::get("/classes", [ClassRegisterController::class, "getListclasses"])->name("classes");
Route::get("/classes/{id}/detail", [ClassRegisterController::class, "detailClass"])->name("classes.detail");
Route::any("/contact", [HomeController::class, "pageContact"])->name("contact");

Route::post("/classes/{idClass}/apply-class", [ClassRegisterController::class, "applyClass"])->name("class.apply");
Route::get("/profile",[UserController::class, "profile"])->name("profile.index");
Route::get("/profile/{idClass}/classes/contract",[UserController::class, "downloadContract"])->name("profile.contract.download");
Route::get("/profile/detail",[UserController::class, "detail"])->name("profile.detail");
Route::get("/profile/card",[UserController::class, "card"])->name("profile.card");
Route::get("/profile/class/recieve",[UserController::class, "recieveClass"])->name("profile.class.recieve");
Route::get("/profile/class/recieved",[UserController::class, "recievedClass"])->name("profile.class.recieved");
Route::any("/profile/password/change",[UserController::class, "changePassword"])->name("profile.password.change");
Route::get("/profile/calendar",[UserController::class, "calendar"])->name("profile.calendar");
Route::get("/profile/calendar/getEvents",[UserController::class, "getEventsCalendar"])->name("profile.calendar.getData");
Route::delete("/profile/calendar/{idcalendar}/delete",[UserController::class, "deleteEvent"])->name("profile.calendar.delete");
Route::post("/profile/calendar",[UserController::class, "updateCalendar"])->name("profile.calendar.update");
Route::post("/profile/avatar/store",[UserController::class, "storeAvatar"])->name("profile.avatar.store");
Route::any("/profile/comment",[UserController::class, "comment"])->name("profile.comment");
Route::post("/api/profile",[UserController::class, "updateProfile"])->name("profile.update");
Route::get('api/administrative-units', [CommonApiController::class, 'getAdministrativeUnits'])->name('api.administrative-units');
Auth::routes();

Route::group(['prefix' => 'laravel-filemanager'], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

app/Models/Subject.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Subject extends Model
{
    use HasFactory;
    protected $table = "subjects";
    protected $guarded = [];
    public function getStatusCustomAttribute($status)
    {
        if($status == ACTIVE) return  "<span class='badge rounded-pill badge-light-primary me-1'>Đang kích hoạt</span>";
        if($status == INACTIVE) return "<span class='badge rounded-pill badge-light-danger me-1'>Chưa kích hoạt</span>";
    }
    public function category() {
        return $this->belongsTo(SubjectCategory::class, "category_subject_id", "id");
    }
}

app/Http/Controllers/Admin/SubjectController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Contract;
use Illuminate\Http\Request;
use App\Http\Traits\ResponseTrait;
use App\Models\Subject;
use App\Models\SubjectCategory;

class SubjectController extends Controller
{
    use ResponseTrait;
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('can:admin.subjects.index')->only('index');
        $this->middleware('can:admin.subjects.store')->only(['create','store']);
        $this->middleware('can:admin.subjects.update')->only(['edit', 'update']);
        $this->middleware('can:admin.subjects.destroy')->only('destroy');
    }
    public function index()
    {
        $subjects = Subject::select("id", "name", "category_subject_id", "status as status_custom")->with("category:id,name")->get();
        return view("backend.subjects.index", compact("subjects"));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $subjectCategories = SubjectCategory::where("status",ACTIVE)->get();
        return view("backend.subjects.create", compact("subjectCategories"));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try {
            Subject::create($request->all());
            $message = $this->response("success", "Thêm hợp đồng thành công");
            return redirect()->route("admin.subjects.index")->with($message);
        } catch (\Throwable $th) {
            info("log:".$th);
            $message = $this->response("error", "Có lỗi xảy ra, vui lòng thử lại");
            return back()->with($message);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Contract  $contract
     * @return \Illuminate\Http\Response
     */
    public function show(Contract $contract)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Contract  $contract
     * @return \Illuminate\Http\Response
     */
    public function edit(Subject $subject)
    {
        $subjectCategories = SubjectCategory::where("status",ACTIVE)->get();
        return view("backend.subjects.edit", compact("subject", "subjectCategories"));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Contract  $contract
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Subject $subject)
    {
        try {
            $subject->update([
                'name' => $request->name,
                'category_subject_id' => $request->category_subject_id,
                'status' => $request->status,
            ]);
            $message = $this->response("success", "Cập nhật môn học thành công");
            return redirect()->route("admin.subjects.index")->with($message);
        } catch (\Throwable $th) {
            info("log:".$th);
            $message = $this->response("error", "Có lỗi xảy ra, vui lòng thử lại");
            return back()->with($message);
        }

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Contract  $contract
     * @return \Illuminate\Http\Response
     */
    public function destroy(Subject $subject)
    {
        try {
            $subject->delete();
            $message = $this->response("success", "Xóa môn học thành công");
            return redirect()->route("admin.subjects.index")->with($message);
        } catch (\Throwable $th) {
            info("log:".$th);
            $message = $this->response("error", "Có lỗi xảy ra, vui lòng thử lại");
            return back()->with($message);
        }
    }
}

resources/views/backend/subjects/create.blade.php
@extends("backend.layouts.master")
@section("content")
<div class="app-content content ">
    <div class="content-overlay"></div>
    <div class="header-navbar-shadow"></div>
    <div class="content-wrapper container-xxl p-0">
        <div class="content-header row">
            <div class="content-header-left col-md-9 col-12 mb-2">
                <div class="row breadcrumbs-top">
                    <div class="col-12">
                        <h2 class="content-header-title float-start mb-0">Thêm mới môn học</h2>
                        {{Breadcrumbs::render('subjects.create')}}
                    </div>
                </div>
            </div>
            <div class="content-header-right text-md-end col-md-3 col-12 d-md-block d-none">
                <div class="mb-1 breadcrumb-right">
                    <div class="dropdown">
                        <button class="btn-icon btn btn-primary btn-round btn-sm dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i data-feather="grid"></i></button>
                        <div class="dropdown-menu dropdown-menu-end"><a class="dropdown-item" href="app-todo.html"><i class="me-1" data-feather="check-square"></i><span class="align-middle">Todo</span></a><a class="dropdown-item" href="app-chat.html"><i class="me-1" data-feather="message-square"></i><span class="align-middle">Chat</span></a><a class="dropdown-item" href="app-email.html"><i class="me-1" data-feather="mail"></i><span class="align-middle">Email</span></a><a class="dropdown-item" href="app-calendar.html"><i class="me-1" data-feather="calendar"></i><span class="align-middle">Calendar</span></a></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="content-body">
            <!-- Validation -->
            <section class="bs-validation">
                <div class="row">
                    <!-- Bootstrap Validation -->
                    <div class="col-md-12 col-12">
                        <div class="card">
                            <div class="card-header">
                                <h4 class="card-title">Thêm môn học</h4>
                            </div>
                            <div class="card-body">
                                <form method="POST" action="{{route("admin.subjects.store")}}" class="needs-validation" enctype="multipart/form-data">
                                    @csrf
                                    <div class="mb-1">
                                        <label class="form-label" for="name">Tên môn học</label>
                                        <input type="text" name="name" id="name" class="form-control" placeholder="Name" required />
                                    </div>
                                    <div class="mb-1">
                                        <label class="form-label" for="category_subject_id">Loại sách</label>
                                        <select class="form-select select2" id="category_subject_id" name="category_subject_id" required>
                                            @foreach ($subjectCategories as $subjectCategory)
                                                <option value="{{$subjectCategory->id}}">{{$subjectCategory->name}}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                    <div class="mb-1">
                                        <label class="form-label" for="status">Trạng thái</label>
                                        <select class="form-select" name="status" id="status" required>
                                            <option value="0">Chưa kích hoạt</option>
                                            <option value="1">Kích hoạt</option>
                                        </select>
                                    </div>
                                    <button type="submit" class="btn btn-primary">Thêm mới</button>
                                </form>
                            </div>
                        </div>
                    </div>
                    <!-- /Bootstrap Validation -->
                </div>
            </section>
            <!-- /Validation -->

        </div>
    </div>
</div>
@endsection
@push('js')
    <script>
        $(".select2").select2();
    </script>
@endpush

resources/views/backend/subjects/edit.blade.php
@extends("backend.layouts.master")
@section("content")
<div class="app-content content ">
    <div class="content-overlay"></div>
    <div class="header-navbar-shadow"></div>
    <div class="content-wrapper container-xxl p-0">
        <div class="content-header row">
            <div class="content-header-left col-md-9 col-12 mb-2">
                <div class="row breadcrumbs-top">
                    <div class="col-12">
                        <h2 class="content-header-title float-start mb-0">Cập nhật môn học</h2>
                        {{Breadcrumbs::render('subjects.show', $subject)}}
                    </div>
                </div>
            </div>
            <div class="content-header-right text-md-end col-md-3 col-12 d-md-block d-none">
                <div class="mb-1 breadcrumb-right">
                    <div class="dropdown">
                        <button class="btn-icon btn btn-primary btn-round btn-sm dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i data-feather="grid"></i></button>
                        <div class="dropdown-menu dropdown-menu-end"><a class="dropdown-item" href="app-todo.html"><i class="me-1" data-feather="check-square"></i><span class="align-middle">Todo</span></a><a class="dropdown-item" href="app-chat.html"><i class="me-1" data-feather="message-square"></i><span class="align-middle">Chat</span></a><a class="dropdown-item" href="app-email.html"><i class="me-1" data-feather="mail"></i><span class="align-middle">Email</span></a><a class="dropdown-item" href="app-calendar.html"><i class="me-1" data-feather="calendar"></i><span class="align-middle">Calendar</span></a></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="content-body">
            <!-- Validation -->
            <section class="bs-validation">
                <div class="row">
                    <!-- Bootstrap Validation -->
                    <div class="col-md-12 col-12">
                        <div class="card">
                            <div class="card-header">
                                <h4 class="card-title">Cập nhật môn học</h4>
                            </div>
                            <div class="card-body">
                                <form method="POST" action="{{route("admin.subjects.update", $subject)}}" class="needs-validation" enctype="multipart/form-data">
                                    @csrf
                                    @method("PUT")
                                    <div class="mb-1">
                                        <label class="form-label" for="name">Tên môn học</label>
                                        <input type="text" name="name" id="name" value="{{$subject->name}}" class="form-control" placeholder="Name" required />
                                    </div>
                                    <div class="mb-1">
                                        <label class="form-label" for="category_subject_id">Loại sách</label>
                                        <select class="form-select select2" id="category_subject_id" name="category_subject_id" required>
                                            @foreach ($subjectCategories as $subjectCategory)
                                                <option {{$subjectCategory->id == $subject->category_subject_id ? "selected" : ""}} value="{{$subjectCategory->id}}">{{$subjectCategory->name}}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                    @include("backend.components.status", ["object"=>$subject])
                                    <button type="submit" class="btn btn-primary">Cập nhật</button>
                                </form>
                            </div>
                        </div>
                    </div>
                    <!-- /Bootstrap Validation -->
                </div>
            </section>
            <!-- /Validation -->

        </div>
    </div>
</div>
@endsection

resources/views/backend/subjects/index.blade.php
@extends("backend.layouts.master")
@section("content")
<div class="app-content content ">
    <div class="content-overlay"></div>
    <div class="header-navbar-shadow"></div>
    <div class="content-wrapper container-xxl p-0">
        <div class="content-header row">
            <div class="content-header-left col-md-9 col-12 mb-2">
                <div class="row breadcrumbs-top">
                    <div class="col-12">
                        <h2 class="content-header-title float-start mb-0">Môn học</h2>
                        {{Breadcrumbs::render('subjects.index')}}
                    </div>
                </div>
            </div>
        </div>
        <div class="content-body">
            <!-- Basic Tables start -->
            <div class="row" id="basic-table">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <a href="{{route("admin.subjects.create")}}" class="btn btn-primary float-right">Thêm mới</a>
                        </div>
                        <div class="table-responsive">
                            <table class="table text-center">
                                <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>Tên môn học</th>
                                        <th>Loại môn học</th>
                                        <th>Trạng thái</th>
                                        <th>Hành động</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @forelse ($subjects as $subject)
                                    <tr>
                                        <td>
                                            <span class="fw-bold">{{$subject->id}}</span>
                                        </td>
                                        <td>{{$subject->name}}</td>
                                        <td>{{$subject->category->name}}</td>
                                        <td>{!! $subject->status_custom !!}</td>
                                        <td class="text-center">
                                           <a href="{{route("admin.subjects.edit",$subject->id)}}"><span class=""><i data-feather='edit'></i></span></a>
                                           <a href="javascript:void(0);"
                                            onclick="if (confirm('Are you sure to delete this record?'))
                                            {document.getElementById('delete-subject-{{ $subject->id }}').submit();} else {return false;}"
                                            class="">
                                            <span class=""><i data-feather='trash'></i></span>
                                            </a>
                                           <form action="{{ route('admin.subjects.destroy', $subject) }}"
                                                method="POST"
                                                id="delete-subject-{{ $subject->id }}" class="d-none">
                                                @csrf
                                                @method('DELETE')
                                            </form>
                                        </td>
                                    </tr>
                                    @empty

                                    @endforelse

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Basic Tables end -->
        </div>
    </div>
</div>
@endsection