routes/admin.php
<?php

use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\Auth\LoginController;
use App\Http\Controllers\Admin\Auth\ForgotPasswordController;
use App\Http\Controllers\Admin\Auth\ResetPasswordController;
use App\Http\Controllers\Admin\ClassController;
use App\Http\Controllers\Admin\ClassRegisterController;
use App\Http\Controllers\Admin\CommonApiController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\ContractController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\admin\SubjectCategoryController;
use App\Http\Controllers\Admin\SubjectController;
use App\Http\Controllers\Admin\UserController;
use Illuminate\Support\Facades\Route;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

Route::get('login', [LoginController::class, 'showLoginForm'])->name('login');
Route::post('login', [LoginController::class, 'login']);

Route::get('logout', [LoginController::class, 'logout'])->name('logout');
// Route::get('logout', [LoginController::class, 'logout']); // @Todo Remove logout GET method

Route::get('password/reset', [ForgotPasswordController::class, 'showLinkRequestForm'])->name('password.request');
Route::post('password/email', [ForgotPasswordController::class, 'sendResetLinkEmail'])->name('password.email');

Route::get('password/reset/{token}', [ResetPasswordController::class, 'showResetForm'])->name('password.reset');
Route::post('password/reset', [ResetPasswordController::class, 'reset'])->name('password.update');

Route::group(['prefix'=>'','as'=>'','middleware' => ['admin.auth']], function(){
    Route::get('dashboard', [DashboardController::class, 'dashboard'])->name("dashboard");
    Route::resource('contracts', ContractController::class);
    Route::resource('subject-categories', SubjectCategoryController::class);
    Route::resource('subjects', SubjectController::class);
    Route::resource('classes', ClassController::class);
    Route::resource('roles', RoleController::class);
    Route::resource('classes-register', ClassRegisterController::class);
    Route::resource('admins', AdminController::class);
    Route::get('api/admins', [AdminController::class, 'getData'])->name('admins.api');
    Route::get('api/classes-register', [ClassRegisterController::class, 'getData'])->name('classes-register.api');
    Route::post('api/classes-register/{id}/calendar', [ClassRegisterController::class, 'addCalendar'])->name('api.classes-register.calendar');
    Route::get('api/classes-register/{id}/filter/tutors', [ClassRegisterController::class, 'filterTutor'])->name('api.classes-register.filter');
    Route::post('api/classes-register/{id}/class/{user_id}/assign', [ClassRegisterController::class, 'assignClass'])->name('api.classes-register.assign');
    Route::delete('api/classes-register/calendar/{id}/delete', [ClassRegisterController::class, 'deleteCalendar'])->name('api.classes-register.calendar.delete');
    Route::get('api/classes-register/{id}/userAssigned', [ClassRegisterController::class, 'getUserAssignee'])->name('api.classes-register.userAssigned');
    Route::get('api/administrative-units', [CommonApiController::class, 'getAdministrativeUnits'])->name('api.administrative-units');
    Route::get('api/calendar/events/{modal_id}/get', [CommonApiController::class, 'getEvents'])->name('api.calendar.events');
    Route::get("profile", [AdminController::class, "profile"])->name("profile");
    Route::post("profile/store", [AdminController::class, "storeProfile"])->name("profile.store");
    Route::post("avatar/store", [AdminController::class, "storeAvatar"])->name("avatar.store");
    Route::get("security", [AdminController::class, "security"])->name("security");
    Route::post("security/store", [AdminController::class, "storeSecurity"])->name("security.store");
    Route::get("users", [UserController::class, "index"])->name("users.index");
    Route::POST("users/{id}/update/status", [UserController::class, "updateStatus"])->name("users.update.status");
    Route::POST("users/{id}/update/honnor", [UserController::class, "updateHonnor"])->name("users.update.honnor");
    Route::get("users/{id}/info", [UserController::class, "getInfoUsers"])->name("users.info");
    Route::get("api/users", [UserController::class, "getData"])->name("users.getData");
});

routes/web.php
<?php

use App\Http\Controllers\Admin\CommonApiController;
use App\Http\Controllers\frontend\ClassRegisterController;
use App\Http\Controllers\Frontend\HomeController;
use App\Http\Controllers\Frontend\UserController;

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get("/",[HomeController::class, "index"])->name("index");
Route::get("/contract",[HomeController::class, "contract"])->name("contract");
Route::get("/classes", [ClassRegisterController::class, "getListclasses"])->name("classes");
Route::get("/classes/{id}/detail", [ClassRegisterController::class, "detailClass"])->name("classes.detail");
Route::any("/contact", [HomeController::class, "pageContact"])->name("contact");

Route::post("/classes/{idClass}/apply-class", [ClassRegisterController::class, "applyClass"])->name("class.apply");
Route::get("/profile",[UserController::class, "profile"])->name("profile.index");
Route::get("/profile/{idClass}/classes/contract",[UserController::class, "downloadContract"])->name("profile.contract.download");
Route::get("/profile/detail",[UserController::class, "detail"])->name("profile.detail");
Route::get("/profile/card",[UserController::class, "card"])->name("profile.card");
Route::get("/profile/class/recieve",[UserController::class, "recieveClass"])->name("profile.class.recieve");
Route::get("/profile/class/recieved",[UserController::class, "recievedClass"])->name("profile.class.recieved");
Route::any("/profile/password/change",[UserController::class, "changePassword"])->name("profile.password.change");
Route::get("/profile/calendar",[UserController::class, "calendar"])->name("profile.calendar");
Route::get("/profile/calendar/getEvents",[UserController::class, "getEventsCalendar"])->name("profile.calendar.getData");
Route::delete("/profile/calendar/{idcalendar}/delete",[UserController::class, "deleteEvent"])->name("profile.calendar.delete");
Route::post("/profile/calendar",[UserController::class, "updateCalendar"])->name("profile.calendar.update");
Route::post("/profile/avatar/store",[UserController::class, "storeAvatar"])->name("profile.avatar.store");
Route::any("/profile/comment",[UserController::class, "comment"])->name("profile.comment");
Route::post("/api/profile",[UserController::class, "updateProfile"])->name("profile.update");
Route::get('api/administrative-units', [CommonApiController::class, 'getAdministrativeUnits'])->name('api.administrative-units');
Auth::routes();

Route::group(['prefix' => 'laravel-filemanager'], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

app/Models/Roles.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Roles extends Model
{
    use HasFactory;
    protected $table = "roles";
    protected $guarded = [];
    public function permissions() {
        return $this->belongsToMany(Permissions::class,"role_permissions","role_id","permission_id");
    }
    public function admins() {
        return $this->belongsToMany(Admin::class,"admin_roles","role_id","admin_id");
    }
}

app/Http/Controllers/Admin/RoleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Permissions;
use App\Models\Roles;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Http\JsonResponse;
use Illuminate\Support\Facades\DB;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $roles = Roles::withCount('admins')->get();
        $permissions = Permissions::where([["level",1],["parent_id",0]])
            ->with("childPermission")
            ->get();
        return view("backend.roles.index", compact("roles", "permissions"));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'name' => ['required'],
            'description' => ['required'],
        ]);
        if ($validator->fails()) {
            return new JsonResponse([
                'success' => false,
                'message' => 'Validation failed',
                'errors' => $validator->errors(),
            ], 422);
        }
        DB::beginTransaction();
        try {
            $role = Roles::create([
                'name'=>$request->name,
                'description'=>$request->description,
            ]);
            if($request->roles) $role->permissions()->sync($request->roles);
            DB::commit();
            return new JsonResponse([
                'success' => true,
                'message' => 'Thêm vai trò thành công',
            ], 200);
        } catch (\Throwable $th) {
            DB::rollback();
            info("log:".$th);
            return new JsonResponse([
                'success' => false,
                'message' => 'Đã có lỗi xảy ra trong quá trình cập nhật quyền',
            ], 500);
        }
        return $request->all();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($roleId)
    {
        try {
            $role = Roles::where("id",$roleId)->with("permissions:id")->first();
            return $role;
        } catch (\Throwable $th) {
            info("Log:".$th);
            return false;
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(), [
            'name' => ['required'],
            'description' => ['required'],
        ]);
        if ($validator->fails()) {
            return new JsonResponse([
                'success' => false,
                'message' => 'Validation failed',
                'errors' => $validator->errors(),
            ], 422);
        }
        DB::beginTransaction();
        try {
            $role = Roles::find($id);
            $role->name = $request->name;
            $role->description = $request->description;
            $role->save();
            if($request->roles) {
                $role->permissions()->sync($request->roles);
            } else $role->permissions()->detach();
            DB::commit();
            return new JsonResponse([
                'success' => true,
                'message' => 'Cập nhật vai trò thành công',
            ], 200);
        } catch (\Throwable $th) {
            DB::rollback();
            info("log:".$th);
            return new JsonResponse([
                'success' => false,
                'message' => 'Đã có lỗi xảy ra trong quá trình cập nhật quyền',
            ], 500);
        }
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        DB::beginTransaction();
        try {
            $role = Roles::find($id);
            $role->permissions()->detach();
            $role->admins()->detach();
            $role->delete();
            DB::commit();
            return new JsonResponse([
                'success' => true,
                'message' => 'Xóa vai trò thành công',
            ], 200);
        } catch (\Throwable $th) {
            DB::rollback();
            info("LOG DELETE ROLE:".$th);
            return new JsonResponse([
                'success' => false,
                'message' => 'Đã có lỗi xảy ra trong quá trình cập nhật quyền',
            ], 500);
        }
    }
}

resources/views/backend/roles/index.blade.php
@extends("backend.layouts.master")
@section("content")
    <!-- BEGIN: Content-->
    <div class="app-content content ">
        <div class="content-overlay"></div>
        <div class="header-navbar-shadow"></div>
        <div class="content-wrapper container-xxl p-0">
            <div class="content-header row">
            </div>
            <div class="content-body">
                <h3>Danh sách vai trò</h3>
                <!-- Role cards -->
                <div class="row">
                    @foreach ($roles as $role)
                    <div class="col-xl-4 col-lg-6 col-md-6">
                        <div class="card">
                            <div class="card-body">
                                <div class="d-flex justify-content-between">
                                    <span>Tổng {{$role->admins_count}} thành viên</span>
                                    <ul class="list-unstyled d-flex align-items-center avatar-group mb-0">
                                        {{-- <li data-bs-toggle="tooltip" data-popup="tooltip-custom" data-bs-placement="top" title="Jimmy Ressula" class="avatar avatar-sm pull-up">
                                            <img class="rounded-circle" src="../../../app-assets/images/avatars/4.png" alt="Avatar" />
                                        </li> --}}
                                    </ul>
                                </div>
                                <div class="d-flex justify-content-between align-items-end mt-1 pt-25">
                                    <div class="role-heading">
                                        <h4 class="fw-bolder">{{$role->name}}</h4>
                                        <a href="javascript:;" class="role-edit-modal" onclick="handleEditRole({{$role->id}}, '{{$role->name}}')">
                                            <small class="fw-bolder">Chỉnh sửa</small>
                                        </a>
                                    </div>
                                    <a href="javascript:void(0);" onclick="handleDeleteRole({{$role->id}})" class="text-body"><i data-feather="delete" class="font-medium-5"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                    @endforeach

                    <div class="col-xl-4 col-lg-6 col-md-6">
                        <div class="card">
                            <div class="row">
                                <div class="col-sm-5">
                                    <div class="d-flex align-items-end justify-content-center h-100">
                                        <img src="{{asset("backend/app-assets/images/illustration/faq-illustrations.svg")}}" class="img-fluid mt-2" alt="Image" width="85" />
                                    </div>
                                </div>
                                <div class="col-sm-7">
                                    <div class="card-body text-sm-end text-center ps-sm-0">
                                        <a href="javascript:void(0)" class="stretched-link text-nowrap add-new-role">
                                            <span class="btn btn-primary mb-1">Thêm vai trò</span>
                                        </a>
                                        <p class="mb-0">Thêm vai trò nếu chưa tồn tại</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!--/ Role cards -->
                <!-- Add Role Modal -->
                <div class="modal fade" id="addRoleModal" tabindex="-1" aria-hidden="true">
                    <div class="modal-dialog modal-lg modal-dialog-centered modal-add-new-role">
                        <div class="modal-content">
                            <div class="modal-header bg-transparent">
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body px-5 pb-5">
                                <div class="text-center mb-4">
                                    <h1 class="role-title">Thềm vai trò</h1>
                                    <p>Cài đặt quyền hạn</p>
                                </div>
                                <!-- Add role form -->
                                <form id="addRoleForm" method="post" action="{{route("admin.roles.store")}}" class="row">
                                    @csrf
                                    <div class="col-12">
                                        <label class="form-label" for="name">Tên vai trò</label>
                                        <input type="text" id="name" name="name" class="form-control"  tabindex="-1" data-msg="Yêu cầu bắt buộc" />
                                    </div>
                                    <div class="col-12">
                                        <label class="form-label" for="description">Mô tả vai trò</label>
                                        <input type="text" id="description" name="description" class="form-control"  tabindex="-1" data-msg="Yêu cầu bắt buộc" />
                                    </div>
                                    <div class="col-12">
                                        <h4 class="mt-2 pt-50">Quyền hạn</h4>
                                        <!-- Permission table -->
                                        <div class="table-responsive">
                                            <table class="table table-flush-spacing">
                                                <tbody>
                                                    <tr>
                                                        <td class="text-nowrap fw-bolder">

                                                        </td>
                                                        <td>
                                                            <div class="form-check">
                                                                <input class="form-check-input" type="checkbox" id="selectAll" />
                                                                <label class="form-check-label" for="selectAll">Chọn tất cả</label>
                                                            </div>
                                                        </td>
                                                    </tr>

                                                        @foreach ($permissions as $permission)
                                                        <tr>
                                                        <td class="text-nowrap fw-bolder">{{$permission->name}}</td>
                                                        <td>
                                                            <div class="d-flex">
                                                                @foreach ($permission->childPermission as $childPermission)
                                                                <div class="form-check me-3 me-lg-5">
                                                                    <input class="form-check-input role-checkbox" type="checkbox" data-id="{{$childPermission->id}}" name="roles[]" value="{{$childPermission->id}}" id="role-{{$childPermission->id}}" />
                                                                    <label class="form-check-label" for="role-{{$childPermission->id}}"> {{$childPermission->name}}</label>
                                                                </div>
                                                                @endforeach
                                                            </div>
                                                        </td>
                                                        </tr>
                                                        @endforeach

                                                </tbody>
                                            </table>
                                        </div>
                                        <!-- Permission table -->
                                    </div>
                                    <div class="col-12 text-center mt-2">
                                        <button type="submit" class="btn btn-primary me-1">Cập nhật</button>
                                        <button type="reset" class="btn btn-outline-secondary" data-bs-dismiss="modal" aria-label="Close">
                                            Đóng
                                        </button>
                                    </div>
                                </form>
                                <!--/ Add role form -->
                            </div>
                        </div>
                    </div>
                </div>
                <!--/ Add Role Modal -->

            </div>
        </div>
    </div>
    <!-- END: Content-->
@endsection

@push("js")
    <script src="{{asset("backend/js/roles-index.js?v=r").rand(0,10)}}"></script>
@endpush