routes/admin.php
<?php

use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\Auth\LoginController;
use App\Http\Controllers\Admin\Auth\ForgotPasswordController;
use App\Http\Controllers\Admin\Auth\ResetPasswordController;
use App\Http\Controllers\Admin\ClassController;
use App\Http\Controllers\Admin\ClassRegisterController;
use App\Http\Controllers\Admin\CommonApiController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\ContractController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\admin\SubjectCategoryController;
use App\Http\Controllers\Admin\SubjectController;
use App\Http\Controllers\Admin\UserController;
use Illuminate\Support\Facades\Route;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

Route::get('login', [LoginController::class, 'showLoginForm'])->name('login');
Route::post('login', [LoginController::class, 'login']);

Route::get('logout', [LoginController::class, 'logout'])->name('logout');
// Route::get('logout', [LoginController::class, 'logout']); // @Todo Remove logout GET method

Route::get('password/reset', [ForgotPasswordController::class, 'showLinkRequestForm'])->name('password.request');
Route::post('password/email', [ForgotPasswordController::class, 'sendResetLinkEmail'])->name('password.email');

Route::get('password/reset/{token}', [ResetPasswordController::class, 'showResetForm'])->name('password.reset');
Route::post('password/reset', [ResetPasswordController::class, 'reset'])->name('password.update');

Route::group(['prefix'=>'','as'=>'','middleware' => ['admin.auth']], function(){
    Route::get('dashboard', [DashboardController::class, 'dashboard'])->name("dashboard");
    Route::resource('contracts', ContractController::class);
    Route::resource('subject-categories', SubjectCategoryController::class);
    Route::resource('subjects', SubjectController::class);
    Route::resource('classes', ClassController::class);
    Route::resource('roles', RoleController::class);
    Route::resource('classes-register', ClassRegisterController::class);
    Route::resource('admins', AdminController::class);
    Route::get('api/admins', [AdminController::class, 'getData'])->name('admins.api');
    Route::get('api/classes-register', [ClassRegisterController::class, 'getData'])->name('classes-register.api');
    Route::post('api/classes-register/{id}/calendar', [ClassRegisterController::class, 'addCalendar'])->name('api.classes-register.calendar');
    Route::get('api/classes-register/{id}/filter/tutors', [ClassRegisterController::class, 'filterTutor'])->name('api.classes-register.filter');
    Route::post('api/classes-register/{id}/class/{user_id}/assign', [ClassRegisterController::class, 'assignClass'])->name('api.classes-register.assign');
    Route::delete('api/classes-register/calendar/{id}/delete', [ClassRegisterController::class, 'deleteCalendar'])->name('api.classes-register.calendar.delete');
    Route::get('api/classes-register/{id}/userAssigned', [ClassRegisterController::class, 'getUserAssignee'])->name('api.classes-register.userAssigned');
    Route::get('api/administrative-units', [CommonApiController::class, 'getAdministrativeUnits'])->name('api.administrative-units');
    Route::get('api/calendar/events/{modal_id}/get', [CommonApiController::class, 'getEvents'])->name('api.calendar.events');
    Route::get("profile", [AdminController::class, "profile"])->name("profile");
    Route::post("profile/store", [AdminController::class, "storeProfile"])->name("profile.store");
    Route::post("avatar/store", [AdminController::class, "storeAvatar"])->name("avatar.store");
    Route::get("security", [AdminController::class, "security"])->name("security");
    Route::post("security/store", [AdminController::class, "storeSecurity"])->name("security.store");
    Route::get("users", [UserController::class, "index"])->name("users.index");
    Route::POST("users/{id}/update/status", [UserController::class, "updateStatus"])->name("users.update.status");
    Route::POST("users/{id}/update/honnor", [UserController::class, "updateHonnor"])->name("users.update.honnor");
    Route::get("users/{id}/info", [UserController::class, "getInfoUsers"])->name("users.info");
    Route::get("api/users", [UserController::class, "getData"])->name("users.getData");
});

routes/web.php
<?php

use App\Http\Controllers\Admin\CommonApiController;
use App\Http\Controllers\frontend\ClassRegisterController;
use App\Http\Controllers\Frontend\HomeController;
use App\Http\Controllers\Frontend\UserController;

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get("/",[HomeController::class, "index"])->name("index");
Route::get("/contract",[HomeController::class, "contract"])->name("contract");
Route::get("/classes", [ClassRegisterController::class, "getListclasses"])->name("classes");
Route::get("/classes/{id}/detail", [ClassRegisterController::class, "detailClass"])->name("classes.detail");
Route::any("/contact", [HomeController::class, "pageContact"])->name("contact");

Route::post("/classes/{idClass}/apply-class", [ClassRegisterController::class, "applyClass"])->name("class.apply");
Route::get("/profile",[UserController::class, "profile"])->name("profile.index");
Route::get("/profile/{idClass}/classes/contract",[UserController::class, "downloadContract"])->name("profile.contract.download");
Route::get("/profile/detail",[UserController::class, "detail"])->name("profile.detail");
Route::get("/profile/card",[UserController::class, "card"])->name("profile.card");
Route::get("/profile/class/recieve",[UserController::class, "recieveClass"])->name("profile.class.recieve");
Route::get("/profile/class/recieved",[UserController::class, "recievedClass"])->name("profile.class.recieved");
Route::any("/profile/password/change",[UserController::class, "changePassword"])->name("profile.password.change");
Route::get("/profile/calendar",[UserController::class, "calendar"])->name("profile.calendar");
Route::get("/profile/calendar/getEvents",[UserController::class, "getEventsCalendar"])->name("profile.calendar.getData");
Route::delete("/profile/calendar/{idcalendar}/delete",[UserController::class, "deleteEvent"])->name("profile.calendar.delete");
Route::post("/profile/calendar",[UserController::class, "updateCalendar"])->name("profile.calendar.update");
Route::post("/profile/avatar/store",[UserController::class, "storeAvatar"])->name("profile.avatar.store");
Route::any("/profile/comment",[UserController::class, "comment"])->name("profile.comment");
Route::post("/api/profile",[UserController::class, "updateProfile"])->name("profile.update");
Route::get('api/administrative-units', [CommonApiController::class, 'getAdministrativeUnits'])->name('api.administrative-units');
Auth::routes();

Route::group(['prefix' => 'laravel-filemanager'], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

app/Models/Contract.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Contract extends Model
{
    use HasFactory;
    const HOP_DONG_NHAN_LOP = 1;
    const HOP_DONG_KHAC = 2;
    protected $table = "contracts";
    protected $guarded = [];

    public function getTypeCustomAttribute($type)
    {
        switch ($type) {
            case self::HOP_DONG_NHAN_LOP:
                return "Hợp đồng nhận lớp";
                break;
            default:
                return "Hợp đồng khác";
                break;
        }
    }
    public function getStatusCustomAttribute($status)
    {
        if($status == ACTIVE) return  "<span class='badge rounded-pill badge-light-primary me-1'>Đang kích hoạt</span>";
        if($status == INACTIVE) return "<span class='badge rounded-pill badge-light-danger me-1'>Chưa kích hoạt</span>";
    }

    public function getCreatedAtCustomtribute($createdAt)
    {
        return Carbon::parse($createdAt)->format("d-m-Y H:i:s");
    }

}

app/Http/Controllers/Admin/ContractController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Contract;
use Illuminate\Http\Request;
use App\Http\Traits\ResponseTrait;

class ContractController extends Controller
{
    use ResponseTrait;

    public function __construct()
    {
        $this->middleware('can:admin.contracts.index')->only('index');
        $this->middleware('can:admin.contracts.store')->only(['create','store']);
        $this->middleware('can:admin.contracts.update')->only(['edit', 'update']);
        $this->middleware('can:admin.contracts.destroy')->only('destroy');
    }



    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $contracts = Contract::select("id","code","title", "content", "created_at as created_at_custom", "type as type_custom", "status as status_custom")->get();
        return view("backend.contracts.index", compact("contracts"));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view("backend.contracts.create");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try {

            $data = (object) $request->all();
            $data->code = "HĐ_".mt_rand(1000000, 9999999);
            Contract::create((array) $data);
            $message = $this->response("success", "Thêm hợp đồng thành công");
            return redirect()->route("admin.contracts.index")->with($message);
        } catch (\Throwable $th) {
            info("log:".$th);
            $message = $this->response("error", "Có lỗi xảy ra, vui lòng thử lại");
            return back()->with($message);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Contract  $contract
     * @return \Illuminate\Http\Response
     */
    public function show(Contract $contract)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Contract  $contract
     * @return \Illuminate\Http\Response
     */
    public function edit(Contract $contract)
    {
        return view("backend.contracts.edit", compact("contract"));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Contract  $contract
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Contract $contract)
    {
        try {
            $contract->update([
                'title' => $request->title,
                'content' => $request->content,
                'type' => $request->type,
                'status' => $request->status,
            ]);
            $message = $this->response("success", "Cập nhật hợp đồng thành công");
            return redirect()->route("admin.contracts.index")->with($message);
        } catch (\Throwable $th) {
            info("log:".$th);
            $message = $this->response("error", "Có lỗi xảy ra, vui lòng thử lại");
            return back()->with($message);
        }

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Contract  $contract
     * @return \Illuminate\Http\Response
     */
    public function destroy(Contract $contract)
    {
        try {
            $contract->delete();
            $message = $this->response("success", "Xóa hợp đồng thành công");
            return redirect()->route("admin.contracts.index")->with($message);
        } catch (\Throwable $th) {
            info("log:".$th);
            $message = $this->response("error", "Có lỗi xảy ra, vui lòng thử lại");
            return back()->with($message);
        }
    }
}

resources/views/backend/contracts/create.blade.php
@extends("backend.layouts.master")
@section("content")
<div class="app-content content ">
    <div class="content-overlay"></div>
    <div class="header-navbar-shadow"></div>
    <div class="content-wrapper container-xxl p-0">
        <div class="content-header row">
            <div class="content-header-left col-md-9 col-12 mb-2">
                <div class="row breadcrumbs-top">
                    <div class="col-12">
                        <h2 class="content-header-title float-start mb-0">Thêm mới hợp đồng</h2>
                        {{Breadcrumbs::render('contracts.create')}}
                    </div>
                </div>
            </div>
            <div class="content-header-right text-md-end col-md-3 col-12 d-md-block d-none">
                <div class="mb-1 breadcrumb-right">
                    <div class="dropdown">
                        <button class="btn-icon btn btn-primary btn-round btn-sm dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i data-feather="grid"></i></button>
                        <div class="dropdown-menu dropdown-menu-end"><a class="dropdown-item" href="app-todo.html"><i class="me-1" data-feather="check-square"></i><span class="align-middle">Todo</span></a><a class="dropdown-item" href="app-chat.html"><i class="me-1" data-feather="message-square"></i><span class="align-middle">Chat</span></a><a class="dropdown-item" href="app-email.html"><i class="me-1" data-feather="mail"></i><span class="align-middle">Email</span></a><a class="dropdown-item" href="app-calendar.html"><i class="me-1" data-feather="calendar"></i><span class="align-middle">Calendar</span></a></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="content-body">
            <!-- Validation -->
            <section class="bs-validation">
                <div class="row">
                    <!-- Bootstrap Validation -->
                    <div class="col-md-12 col-12">
                        <div class="card">
                            <div class="card-header">
                                <h4 class="card-title">Thêm hợp đồng</h4>
                            </div>
                            <div class="card-body">
                                <form method="POST" action="{{route("admin.contracts.store")}}" class="needs-validation" enctype="multipart/form-data">
                                    @csrf
                                    <div class="mb-1">
                                        <label class="form-label" for="title">Tên hợp đồng</label>
                                        <input type="text" name="title" id="title" class="form-control" placeholder="Name" required />
                                    </div>
                                    <div class="mb-1">
                                        <label class="form-label" for="content">Nội dung</label>
                                        <textarea name="content" id="content" rows="20"></textarea>
                                    </div>
                                    <div class="mb-1">
                                        <label class="form-label" for="type">Loại hợp đồng</label>
                                        <select class="form-select" id="type" name="type" required>
                                            <option value="1">Hợp đồng gia sư</option>
                                            <option value="2">Hợp đồng khác</option>
                                        </select>
                                    </div>
                                    <div class="mb-1">
                                        <label class="form-label" for="status">Trạng thái</label>
                                        <select class="form-select" name="status" id="status" required>
                                            <option value="0">Chưa kích hoạt</option>
                                            <option value="1">Kích hoạt</option>
                                        </select>
                                    </div>
                                    <button type="submit" class="btn btn-primary">Thêm mới</button>
                                </form>
                            </div>
                        </div>
                    </div>
                    <!-- /Bootstrap Validation -->
                </div>
            </section>
            <!-- /Validation -->

        </div>
    </div>
</div>
@endsection

resources/views/backend/contracts/edit.blade.php
@extends("backend.layouts.master")
@section("content")
<div class="app-content content ">
    <div class="content-overlay"></div>
    <div class="header-navbar-shadow"></div>
    <div class="content-wrapper container-xxl p-0">
        <div class="content-header row">
            <div class="content-header-left col-md-9 col-12 mb-2">
                <div class="row breadcrumbs-top">
                    <div class="col-12">
                        <h2 class="content-header-title float-start mb-0">Cập nhật hợp đồng</h2>
                        {{Breadcrumbs::render('contracts.show', $contract)}}
                    </div>
                </div>
            </div>
            <div class="content-header-right text-md-end col-md-3 col-12 d-md-block d-none">
                <div class="mb-1 breadcrumb-right">
                    <div class="dropdown">
                        <button class="btn-icon btn btn-primary btn-round btn-sm dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i data-feather="grid"></i></button>
                        <div class="dropdown-menu dropdown-menu-end"><a class="dropdown-item" href="app-todo.html"><i class="me-1" data-feather="check-square"></i><span class="align-middle">Todo</span></a><a class="dropdown-item" href="app-chat.html"><i class="me-1" data-feather="message-square"></i><span class="align-middle">Chat</span></a><a class="dropdown-item" href="app-email.html"><i class="me-1" data-feather="mail"></i><span class="align-middle">Email</span></a><a class="dropdown-item" href="app-calendar.html"><i class="me-1" data-feather="calendar"></i><span class="align-middle">Calendar</span></a></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="content-body">
            <!-- Validation -->
            <section class="bs-validation">
                <div class="row">
                    <!-- Bootstrap Validation -->
                    <div class="col-md-12 col-12">
                        <div class="card">
                            <div class="card-header">
                                <h4 class="card-title">Cập nhật hợp đồng</h4>
                            </div>
                            <div class="card-body">
                                <form method="post" action="{{route("admin.contracts.update",$contract->id)}}" class="needs-validation" enctype="multipart/form-data">
                                    @csrf
                                    @method('PATCH')
                                    <div class="mb-1">
                                        <label class="form-label" for="title">Tên hợp đồng</label>
                                        <input type="text" name="title" id="title" class="form-control" placeholder="Name" value="{{$contract->title}}" required />
                                    </div>
                                    <div class="mb-1">
                                        <label class="form-label" for="content">Nội dung</label>
                                        <textarea name="content" id="content" rows="20">{!! $contract->content !!}</textarea>
                                    </div>
                                    <div class="mb-1">
                                        <label class="form-label" for="type">Loại hợp đồng</label>
                                        <select class="form-select" id="type" name="type" required>
                                            <option {{$contract->type == 1 ? "selected" : ""}}  value="1">Hợp đồng gia sư</option>
                                            <option {{$contract->type == 2 ? "selected" : ""}}  value="2">Hợp đồng khác</option>
                                        </select>
                                    </div>
                                    <div class="mb-1">
                                        <label class="form-label" for="status">Trạng thái</label>
                                        <select class="form-select" name="status" id="status" required>
                                            <option {{$contract->status == INACTIVE ? "selected" : ""}}  value="0">Chưa kích hoạt</option>
                                            <option {{$contract->status == ACTIVE ? "selected" : ""}}  value="1">Kích hoạt</option>
                                        </select>
                                    </div>
                                    <button type="submit" class="btn btn-primary">Cập nhật</button>
                                </form>
                            </div>
                        </div>
                    </div>
                    <!-- /Bootstrap Validation -->
                </div>
            </section>
            <!-- /Validation -->

        </div>
    </div>
</div>
@endsection

resources/views/backend/contracts/index.blade.php
@extends("backend.layouts.master")
@section("content")
<div class="app-content content ">
    <div class="content-overlay"></div>
    <div class="header-navbar-shadow"></div>
    <div class="content-wrapper container-xxl p-0">
        <div class="content-header row">
            <div class="content-header-left col-md-9 col-12 mb-2">
                <div class="row breadcrumbs-top">
                    <div class="col-12">
                        <h2 class="content-header-title float-start mb-0">Hợp đồng</h2>
                        {{Breadcrumbs::render('contracts.index')}}
                    </div>
                </div>
            </div>
        </div>
        <div class="content-body">
            <!-- Basic Tables start -->
            <div class="row" id="basic-table">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <a href="{{route("admin.contracts.create")}}" class="btn btn-primary float-right">Thêm mới</a>
                        </div>
                        <div class="table-responsive">
                            <table class="table text-center">
                                <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>Mã hợp đồng</th>
                                        <th>Tên hợp đồng</th>
                                        <th>Loại hợp đồng</th>
                                        <th>Trạng thái</th>
                                        <th>Ngày tạo</th>
                                        <th>Hành động</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @forelse ($contracts as $contract)
                                    <tr>
                                        <td>
                                            <span class="fw-bold">{{$contract->id}}</span>
                                        </td>
                                        <td>{{$contract->code}}</td>
                                        <td>{{$contract->title}}</td>
                                        <td>{{$contract->type_custom}}</td>
                                        <td>{!! $contract->status_custom !!}</td>
                                        <td>{{$contract->created_at_custom}}</td>
                                        <td class="text-center">
                                           <a href="{{route("admin.contracts.edit",$contract->id)}}"><span class=""><i data-feather='edit'></i></span></a>
                                           <a href="javascript:void(0);"
                                            onclick="if (confirm('Are you sure to delete this record?'))
                                            {document.getElementById('delete-contract-{{ $contract->id }}').submit();} else {return false;}"
                                            class="">
                                            <span class=""><i data-feather='trash'></i></span>
                                            </a>
                                           <form action="{{ route('admin.contracts.destroy', $contract) }}"
                                                method="POST"
                                                id="delete-contract-{{ $contract->id }}" class="d-none">
                                                @csrf
                                                @method('DELETE')
                                            </form>
                                        </td>
                                    </tr>
                                    @empty

                                    @endforelse

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Basic Tables end -->
        </div>
    </div>
</div>

@endsection